### ISSUE TITLE
Move to TypeScript

### ISSUE THREAD

**Issue by M4GNV5** [neuland-ingolstadt/neuland.app#48]
Not getting compiletime errors or even IDE hints when misspelling a field or simply trying to access a non existant member is annoying and results in bugs which could have been prevented in the first place.

nextjs has great typescript support. However we will need to put in some work and convert all our libraries, components and pages adding typescript annotations.

**Comment by FabianSimonGross** [comment]
In Order to complete this issue we discussed splitting up the issues so that smaller chunks can be completed by different people

- [ ] 1. Update TypeScript Compilation #267 
- [ ] 2. Backend/Backend-Utils #251 
- [ ] 3. Fetch/Hooks/lib-stuff  #252 
- [ ] 4. API #253 
- [ ] 5. Components #254  
- [ ] 6. Pages #255
