### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/neuland.app#96]
We should support at least English to make life for international students easier

**Comment by M4GNV5** [comment]
i made good experiences with the [i18nnext](https://www.i18next.com/) tool, which is available in nextjs through [next-i18next](https://www.npmjs.com/package/next-i18next).

I guess any i18n lib would suffice though.

**Comment by FabianSimonGross** [comment]
In Order to complete this issue we discussed splitting up the issues so that smaller chunks can be completed by different people.

- [ ] Login-Page/Profile-Page/Food-Page i18
- [ ] Calender-Page/Events-Page i18
- [ ] Mobility-Page/Events-Page i18
- [ ] Grades-Page/Lecturers-Page i18
- [ ] Timetable-Page/Room-Page i18
- [ ] Dashboard-Page i18
